### PR TITLE
[Hot fix] test when pop size is not constant was failing

### PR DESCRIPTION
**Pull request by gvegayon**
Removed sampling of size pop and added an arbitrary site_pop value to ensure the pre_processing fails (passing the test 😋)

### CODE REVIEW

**Review by kaitejohnson — DISMISSED** [review]
LGTM, looks like CI isn't passing though?

**Comment by gvegayon** [comment]
Yes, there is an error with rlang or something. @dylanhmorris, could you take a look too?

**Comment by kaitejohnson** [comment]
@gvegayon Sorry for the delay on this, I found the issue which was that the `cbind` was making duplicate column names which was throwing off the error message. I made some changes but still used your suggested `seq_len()` to modify pop size.

**Review by kaitejohnson — DISMISSED** [review]
LGTM now that is fixed!

**Comment by gvegayon** [comment]
@dylanhmorris, can you approve this PR? We need another approve other than @kaitejohnson for merging.

**Review by dylanhmorris — APPROVED** [review]
One wording tweak you can take or leave. Thanks both for looking into this!

**Review by dylanhmorris — APPROVED** [review]

**Pull request merged**
