### PR TITLE
163 expand R version 

### PR DESCRIPTION
**Pull request by kaitejohnson**
Attempting to run install of package with multiple R versions in CI. Not sure if there's a more elegant way to do this, but this seemed to work. I think it would make sense to always test both the minimum and latest R release?

### CODE REVIEW

**Review by dylanhmorris — COMMENTED** [review]
This will work and looks solid, but to DRYify it you can use this: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow

If you're inspired, give it a try. If not, we can merge as is and make an issue to replace this with that.

**Comment by kaitejohnson** [comment]
Hmm I wonder if this only works on an array of numerics, whereas `r-version` expects only a string, number, or boolean (not an array):
image.

**Comment by kaitejohnson** [comment]
I think this is ready for review but we'd want to change the github actions rulesets to `check-package` to `check-package (4.1.0)` and `check-package (release)` once merged

**Review by dylanhmorris — APPROVED** [review]
LGTM, thanks @kaitejohnson. I have updated the branch protection rule.

**Comment by kaitejohnson** [comment]
TY! Going to do the same on the other repo

**Pull request merged**
